### ISSUE TITLE
Only first instance of Item Embed widget displays on page

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1150] opened 2015-05-11 20:47 UTC
If you include more than one Item Embed widget on a single page, it appears that the first widget is shown correctly, but the images for the second one are not. It looks like the images are not included in the generated HTML. 

![tem-embed-problem](https://cloud.githubusercontent.com/assets/101482/7574699/2cd49434-f7e4-11e4-8017-83ae70c8172c.png)

**Comment by cbeer** [comment] 2015-05-11 21:02
I see the embed code in the HTML, but the `.sul-embed-container ` is marked as `display: none`. @jkeck , is there logic in sul-embed that might be causing this?

**Comment by jkeck** [comment] 2015-05-11 21:52
Hmm, is this loading via iFrames or pulling the content directly in the page?

**Comment by cbeer** [comment] 2015-05-11 21:57
We pull it directly into the page. Maybe we should try iframes? I don't think we're styling the content or anything like that..

**Comment by cbeer** [comment] 2015-05-11 21:58
Ah, because we're embedding it directly, I bet we're running into problems with duplicate IDs here:

https://github.com/sul-dlss/sul-embed/blob/master/app/assets/javascripts/modules/common_viewer_behavior.js#L30

**Comment by jkeck** [comment] 2015-05-11 21:58
Yeah, although I'm not sure that'll work w/ the standard oEmbed stuff (because we always return the content and it would need some additional markup do be iframe-able).

My concern is we have some improperly scoped javascript that is executing from the 2nd instance on the 1st instance.

**Comment by jkeck** [comment] 2015-05-11 21:58
iframe will fix the scoping.  I'm going to create a ticket in the SUL Embed project to fix that.

**Comment by jkeck** [comment] 2015-05-11 22:02
sul-dlss/sul-embed#236

**Comment by cbeer** [comment] 2015-11-19 04:29
With the new sul-embed, we should check if this is fixed.

**Comment by ggeisler** [comment] 2015-11-19 17:17
It doesn't appear to be fixed. The page below has two Item Embed widgets added to it. The first one displays fine, the second doesn't display. The  `.sul-embed-container ` class of the second  has `display: none`, same as when this ticket was originated.

https://exhibits.stanford.edu/test-exhibit-for-cb/default-exhibit

**Comment by mjgiarlo** [comment] 2016-07-13 18:55
I may be going about reproducing this bug all wrong, because this is what I see:

![screenshot from 2016-07-13 11-54-27](https://cloud.githubusercontent.com/assets/131982/16815893/a011913c-48f0-11e6-9b72-ad3e6ac653e6.png)

Is this issue already resolved or should I follow other steps to reproduce the bug? @cbeer @ggeisler @jcoyne

**Comment by cbeer** [comment] 2016-07-13 19:11
I think this bug was probably misfiled (although #1454 might be a problem here..); I think @ggeisler was thinking about our sul-embed viewer in sul-dlss/exhibits.

**Comment by ggeisler** [comment] 2016-07-13 19:18
Yes, the ticket should've done into the Exhibits repo (it was filed over a year ago, and I think we (or at least I) weren't as conscious about which repo to assign tickets to at that time.

All of the information about the bug is still correct, though. But it is the "Item Embed" widget that is the issue. I just confirmed on -prod that this is still a problem.

**Comment by ggeisler** [comment] 2016-07-13 19:19
I guess I should create a new ticket in Exhibits and close this one?

**Comment by mjgiarlo** [comment] 2016-07-13 20:36
Sounds good, @ggeisler and @cbeer. Thanks!

**Closed** 2016-07-13 20:50 UTC
Labels: bug, ready
